HTML-755 Timezones, Update the datepicker and UiFramework version
openmrs/openmrs-module-uicommons pull request #85
Opened 2021-03-01 17:31 UTC by icrc-jfigueiredo

Update the datepicker component to use timezones
Update UiFramework version from 3.8 to 3.21.0-SNAPSHOT to be possible to use the utils handletimezone function.

2021-03-02 15:08 UTC, mogoodrich commented
Was going to review, but saw it was still in draft... feel free to ping me when it's ready...

2021-04-12 10:25 UTC, mks-d requested changes

2021-04-12 10:25 UTC, mks-d commented on omod/src/main/webapp/fragments/field/datetimepicker.gsp
> +        if( ui.handleTimeZones() ) {
→ `ui.convertTimezones()`

2021-04-12 10:25 UTC, mks-d commented on omod/src/main/webapp/fragments/field/datetimepicker.gsp
> +            <% if (ui.handleTimeZones()) { %>
→ `ui.convertTimezones()`

2021-04-12 10:25 UTC, mks-d commented on omod/src/main/webapp/fragments/field/datetimepicker.gsp
> +        }else{
→ `} else {` (spacing)

2021-04-12 10:25 UTC, mks-d commented on omod/src/main/webapp/fragments/field/datetimepicker.gsp
> +            <% }else{ %>
→ `} else {` (spacing)

2021-04-12 10:25 UTC, mks-d commented on omod/src/main/webapp/fragments/field/datetimepicker.gsp
> +            <% }else{ %>
→ `} else {` (spacing)

2021-05-06 17:25 UTC, merged